"""empty message

Revision ID: 98bb7e056e01
Revises: 
Create Date: 2023-05-15 23:38:24.856282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb7e056e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_roles_title'), ['title'], unique=True)

    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_users_username'))

    op.drop_table('tbl_users')
    with op.batch_alter_table('tbl_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_roles_title'))

    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
